### ISSUE TITLE
Exception on JIRA 7.3.6

### ISSUE THREAD

**Issue by gonchik** [gonchik/jira-prometheus-exporter#1]
> 

2017-09-30 18:20:35,219 UpmAsynchronousTaskManager:thread-1 WARN gonchik.tsymzhitov 1094x989x3 z6xbw3 10.75.137.14,127.0.0.1 /rest/plugins/1.0/available/featured [c.a.u.core.install.DefaultPluginInstallationService] com.atlassian.upm.spi.PluginInstallException: Unknown error, plugin not installed
com.atlassian.upm.spi.PluginInstallException: Unknown error, plugin not installed
        at com.atlassian.upm.core.install.AbstractPluginInstallHandler.installArtifact(AbstractPluginInstallHandler.java:122)
        at com.atlassian.upm.core.install.JarPluginInstallHandler.installPluginInternal(JarPluginInstallHandler.java:52)
        at com.atlassian.upm.core.install.AbstractPluginInstallHandler.installPlugin(AbstractPluginInstallHandler.java:60)
        at com.atlassian.upm.core.install.DefaultPluginInstallationService.execute(DefaultPluginInstallationService.java:117)
        at com.atlassian.upm.core.install.DefaultPluginInstallationService.install(DefaultPluginInstallationService.java:91)
        at com.atlassian.upm.install.UpmPluginInstallationService.install(UpmPluginInstallationService.java:97)
        at com.atlassian.upm.core.rest.resources.install.InstallTask.installFromFile(InstallTask.java:156)
        at com.atlassian.upm.core.rest.resources.install.InstallFromFileTask.executeTask(InstallFromFileTask.java:37)
        at com.atlassian.upm.core.rest.resources.install.InstallTask.run(InstallTask.java:81)
        at com.atlassian.upm.core.async.AsynchronousTaskManager.executeTask(AsynchronousTaskManager.java:124)
        at com.atlassian.upm.core.async.AsynchronousTaskManager$1.call(AsynchronousTaskManager.java:102)
        at com.atlassian.upm.core.async.AsynchronousTaskManager$1.call(AsynchronousTaskManager.java:99)
        at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

>

**Comment by gonchik** [comment]
Second Exception:
0)
        at com.atlassian.upm.core.install.DefaultPluginInstallationService.execute(DefaultPluginInstallationService.java:117)
        at com.atlassian.upm.core.install.DefaultPluginInstallationService.install(DefaultPluginInstallationService.java:91)
        at com.atlassian.upm.install.UpmPluginInstallationService.install(UpmPluginInstallationService.java:97)
        at com.atlassian.upm.core.rest.resources.install.InstallTask.installFromFile(InstallTask.java:156)
        at com.atlassian.upm.core.rest.resources.install.InstallFromFileTask.executeTask(InstallFromFileTask.java:37)
        at com.atlassian.upm.core.rest.resources.install.InstallTask.run(InstallTask.java:81)
        at com.atlassian.upm.core.async.AsynchronousTaskManager.executeTask(AsynchronousTaskManager.java:124)
        at com.atlassian.upm.core.async.AsynchronousTaskManager$1.call(AsynchronousTaskManager.java:102)
        at com.atlassian.upm.core.async.AsynchronousTaskManager$1.call(AsynchronousTaskManager.java:99)
        at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: atlassian-data-center-compatible=true and atlassian-data-center-compatible=true
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)

**Comment by gonchik** [comment]
This commit has helped -> 777e5f763d1c5850d853e1275d1691ddd037c095
